name: Build and Test

on:
  push:
  pull_request:

jobs:
  build-test-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Build & Test
        run: mvn -B clean test
      - name: Package
        run: mvn -B -DskipTests package
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: number-range-summarizer
          path: target/number-range-summarizer-*.jar
